### ISSUE TITLE
website does not work

### ISSUE THREAD

**Issue by LuChao1** [cda-tum/ddvis#105]
In the website https://www.cda.cit.tum.de/app/ddvis/, when I fill up the qasm code on algorithm 1 and algorithm 2, the quantum decision diagram block in the middle always shows a turning circle and it does not show a decision diagram at all. When I click the colored button on the bottom left, the website is not responding.

**Comment by hillmich** [comment]
At this point I'm quite sure the bug is caused by https://github.com/cda-tum/dd_package/pull/104. Changing the type of `idx` from `short` to `std::uint_fast8_t` caused the output stream to handle the values differently.
