### ISSUE TITLE
Measurements are broken

### ISSUE THREAD

**Issue by burgholzer** [cda-tum/ddvis#142]
Measurements don't seem to work at the moment which might be due to some update of an underlying component. The warning is shown in the screenshot below
![image](https://user-images.githubusercontent.com/6358767/217304522-b22cea3d-4ab2-406b-bad2-1bb1feaae4fd.png)

**Comment by hillmich** [comment]
I think the problem is a missing dependency, namely `jquery-ui`. I cannot test it right know since node is weirdly not starting on my system. I'll create a PR with `jquery-ui` added and maybe somebody can try locally?

**Comment by burgholzer** [comment]
I'll try it. But the changes look good to me.
